### ISSUE TITLE
Feature request: Option to draw 4 beats/1 bar

### ISSUE THREAD

**Issue by crshrprt** [ardura/Scrollscope#11]
At the moment Sync Beat shows one beat at time, so for higher BPM the waveform will be refreshed very fast.
Would it be possible to have an option to have 4 beats/1 bar visible?

**Comment by ardura** [comment]
Tested in Ardour and FL with latest version, both sync and alternate sync work now as expected
![image](https://github.com/ardura/Scrollscope/assets/31751444/da006130-696e-45db-b612-e133860e8367)
