### ISSUE TITLE
Feature Request: Draw waveform from left to right by default

### ISSUE THREAD

**Issue by crshrprt** [ardura/Scrollscope#12]
I noticed that Scrollscope draws the waveform from right to left by default, but then when Beat Sync is enabled it draws the waveform from left to right. 
It would be less confusing to draw the waveform from left to right by default, even when Beat Sync is not enabled.

**Comment by ardura** [comment]
I ended up linking the Sync to toggle Flip when enabled or disabled, but Flip can still be decided by user independently. This keeps the waveform facing the same way when sync is enabled/disabled.
