### ISSUE TITLE
Waveform jitter

### ISSUE THREAD

**Issue by crshrprt** [ardura/Scrollscope#13]
In case it will be helpful for tracking down the problem with the waveform jitter here's a list of DAWs/host I tried on Linux when testing [fixing-sync-other-daws](https://github.com/ardura/Scrollscope/tree/fixing-sync-other-daws) branch. 

I encountered jitter in:
Ardour 8.2
Carla 2.5.8
Bespoke Synth Nightly [611103f](https://github.com/BespokeSynth/BespokeSynth/commit/611103fa9540433ae89e7bb75cca7b274228dab0) (initially it seemed not affected, but after a while it was noticeable)

**Comment by ardura** [comment]
Note to whoever works this (or myself for later) - this is probably related to different buffers used in different DAWs altering the timing so it might be easier to change the plugin to go sample-by-sample in processing rather than buffer by buffer. Either that or it is an issue in the nih-plug context.transport() stuff for calculating beat position based off the information the DAW gives the plugin.

**Comment by crshrprt** [comment]
No preroll, it happens also in hosts without that feature.

**Comment by ardura** [comment]
There's something weird with Ardour on Windows where the Beat displayed isn't the tracked beat from the timeline. I'm thinking this is either miscalculation from rounding errors or some sort of lag between the audio thread and the GUI thread. Even then there is still some jitter with the different solutions I've tried. So I have tried to minimize it where I can. I think we should leave this issue open, but I've updated the project with my changes so far.

**Comment by ardura** [comment]
https://github.com/ardura/Scrollscope/commit/1cfbd8f9b91068670926d37e3c8a7b86c6ff6ad7 has the latest changes lessening some of the jitter but it's still there unfortunately.

**Comment by ardura** [comment]
Can you try the latest release build and see if the jitter got better for you?

**Comment by crshrprt** [comment]
In latest version jitter is better, waveform's start still moves in Ardour but it seems a bit more predictable:

https://github.com/ardura/Scrollscope/assets/114294020/5dbae2e3-b96a-4120-8ea6-972742d475a6

In BespokeSynth waveform's start is more stable. In both DAWs the bar synced view is "broken", only a a few ms buffer is displayed:

https://github.com/ardura/Scrollscope/assets/114294020/e0f3a023-9d34-4d3b-be6b-0ff14ea520be

**Comment by ardura** [comment]
Dang I was hoping that would have fixed it. I'll try and revisit this again soon. I thought of another alternative as well:
I'm wondering if I can try to track it manually too. Based off the sample rate and BPM reported to the plugin, I can start counting samples when the DAW reports it is playing vs stopped in its timeline, then calculate the amount of samples each beat or bar *should* be to redraw. I'll play with that iea if it's feasible too.

**Comment by ardura** [comment]
Hey @crshrprt do you use a specific timeline sync in Ardour + your other hosts? I saw in the Ardour manual that MTC timeline control limits the frame rate and that could be part of the issue.

Do you use any external midi timing control or JACK?

**Comment by crshrprt** [comment]
In my tests in Ardour and BespokeSynth I used the internal transport, no external clock.
The same jitter in Ardour is noticeable also when using JACK as external transport master, there isn't much difference.

**Comment by ardura** [comment]
Okay I think I got it fixed now, can you try with the latest release? I tested in Ardour and was able to get nicer beat sync happening :)
