### ISSUE TITLE
Waveforms are tiny after latest updates

### ISSUE THREAD

**Issue by crshrprt** [ardura/Scrollscope#17]
After latest commits, presumably after #16  waveforms have become really tiny, regardless of the settings (ms, skip, etc):

![2024-02-16_13 04 41 948](https://github.com/ardura/Scrollscope/assets/114294020/972e6a4e-e865-4a0b-9a13-73f3bb8e302f)

**Comment by ardura** [comment]
Deleted my comment because I compared the last release binary to this one running the same inputs and they're different. Still looking at this

**Comment by ardura** [comment]
Hey crshrpt this should be fixed now. Looks like some of the jank I did to get the aux inputs working right didn't evaluate the modulus right when compared to the regular input signal when the skip value changed. That's fixed now :) here is opening with default settings
![image](https://github.com/ardura/Scrollscope/assets/31751444/86ccb982-7b6e-4e88-9a63-e2d909b74ee5)
