### ISSUE TITLE
macos ARM binary not found

### ISSUE THREAD

**Issue by Jurek-Raben** [ardura/Scrollscope#19]
Any chance to get an M1 arm build / U2B, too?

**Comment by ardura** [comment]
I can definitely try to do an M1 binary, afaik there is no way to make a universal binary with the GitHub runners but I'll do some research on it. I don't have a Mac so I make the builds using the GitHub hosted machines but I'll see what I can do.

In case neither of those works though, I know Ableton can run some older MacOs built VST3 with Rosetta. Which DAW are you using?

**Comment by Jurek-Raben** [comment]
Hi I am using Bitwig and Renoise on a Mac M1 Pro arm system.

**Comment by ardura** [comment]
[scrollscope_v130_macos_m1.zip](https://github.com/ardura/Scrollscope/files/15151369/scrollscope_v130_macos_m1.zip)
Can you try with the following and let me know if that works?

**Comment by Jurek-Raben** [comment]
Both builds work flawlessly in Renoise and Bitwig.

**Comment by ardura** [comment]
Glad to hear it! I'll add the M1 build to the release page and subsequent updates. Let me know if you run into more issues :)
