### ISSUE TITLE
FR: Smoother scrolling / screen sync with 60Hz + showing timing info

### ISSUE THREAD

**Issue by Jurek-Raben** [ardura/Scrollscope#20]
Hi,

here are two feature requests:

- Smoother scrolling, so the output really snycs to the screen refresh rate, e.g. 60Hz. Maybe that's possible, if drawing mode is set to async / gpu?

- Why not showing the timing information that the vst host delivers? Like the measure bars scrolling with the waveform, so you could very exactly also have information about the timing of the waveform, does it exactly start on point etc.

Thanks for consideration!

**Comment by ardura** [comment]
Hello! If you turn the skip value down, the plugin should redraw earlier in the samples. Also lower timings cause faster redraws. Is that what you mean?

That's a great idea on your second point, I'll see about including that in the next update 👍

**Comment by ardura** [comment]
Closing since this is implemented now
