### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by grogcw** [ardura/Scrollscope#21]
Hi !

Great project, but may I interest you into having some extra features like :

- some type of personalization (json based, css like themes)
- ability to disable frequency markers in spectrum mode
- spectrum bands instead of line (winamp style)
AND
- a standalone "binary version" with the ability to have an audio interface as input

Keep the good work,

Cheers !

**Comment by ardura** [comment]
Hey grogcw! I do like your personalization idea, but it gets a little tricky when done from a VST since different OSs have different paths. I am picturing something in your home/docs folder like scrollscope.conf with colors in it for the different UI elements. Is that what you're thinking?

What OS are you on? I'm not sure how a standalone would work on Mac or Linux to be honest but I can look into it. I see what you're getting at 👍

The other suggestions about spectrum bands and frequency mode I can definitely do in the next update 🔥

**Comment by grogcw** [comment]
Hi !

I'm mainly using MacOS as a daily driver, but I'd fancy a Windows version of the standalone, may it be possible to achieve.

For the customization, you surely could have a satellite file in the same folder as the plugin for exemple, or, as you mentionned it, in the "Documents" of the user's path.

Glad you could look into the bands display mode ! 🔥 

If needed, I can guinea pig your VST builds on <insert an OS family here> if you want. 😄 


Cheers !

**Comment by ardura** [comment]
Right now I have some functionality for color customization in:
![image](https://github.com/ardura/Scrollscope/assets/31751444/e820a736-2a6a-4da1-8cc5-1fbcce5a29b8)

I've also done the frequency marker disable control and the standalone version, just trying to figure out the bars then will make an update.

**Comment by ardura** [comment]
Right now the config looks like the following (RGB colors):

[ui_colors]
background = 40,40,40
guidelines = 160,160,160
ui_main_color = 239,123,69
user_main = 239,123,69
user_aux_1 = 14,177,210
user_aux_2 = 50,255,40
user_aux_3 = 0,153,255
user_aux_4 = 255,0,255
user_aux_5 = 230,80,80
user_sum_line = 248,255,31
inactive_bg = 60,60,60

**Comment by grogcw** [comment]
Seems very promising !

**Comment by ardura** [comment]
Can you try the latest release build?

**Comment by grogcw** [comment]
Hi !

It seems like the VST3 is working fine on BigSur (11.7), but the standalone has been compiled for Monterey (12) so I'll compile it for it as soon as possible. (I'll try the standalone in a near future on Monterey.)

The "bands" mode is cool, but if I may suggest a slight improvement (again), would that be possible to have bands all across the graph and not "only" at some frequencies ?

I know the curve is supposed to be log() based, but I'm sure that with some math trickery you could have it displayed "linearly" and fill up the entire graph 😄 

Good work anyway,

Cheers !

**Comment by ardura** [comment]
> The "bands" mode is cool, but if I may suggest a slight improvement (again), would that be possible to have bands all across the graph and not "only" at some frequencies ?

Done, it's in the latest release now. That math trickery wasn't too bad actually :)
