### ISSUE TITLE
color fill

### ISSUE THREAD

**Issue by undecideduser8** [ardura/Scrollscope#24]
would be nice to have color fill the line stroke

**Comment by ardura** [comment]
Hi undecideduser8! Do you mean like filling under the frequency analyzer with a color?

**Comment by undecideduser8** [comment]
> Hi undecideduser8! Do you mean like filling under the frequency analyzer with a color?

Yes

**Comment by undecideduser8** [comment]
something like this
![Untitled_ - Ableton Live 12 Suite 5_8_2024 9_04_25 PM](https://github.com/ardura/Scrollscope/assets/123988086/e1a8651b-521f-44bd-b6d3-2ae02bcc2c58)

**Comment by ardura** [comment]
I'll look into this more soon, I've just been working on my other repositories lately.

**Comment by ardura** [comment]
So far I haven't been able to figure this out with filling the lines the way they are normally drawn with the GUI library I'm using, BUT I did figure out this kinda-workaround of making it into bars that "fill" as they stack:
![image](https://github.com/ardura/Scrollscope/assets/31751444/6301c291-8f4e-4aa1-ad1a-1e46a4bbe1f1)
So I'll make a few more code changes and then this will probably be the result :)

**Comment by ardura** [comment]
The oscilloscope uses a line plotting library so I'm looking into how I can fill it in there as well.

**Comment by undecideduser8** [comment]
btw this is the best oscilloscope vst i love it!

**Comment by ardura** [comment]
Added to new release, thanks!
