### ISSUE TITLE
Releases for MacOS get blocked by Apple

### ISSUE THREAD

**Issue by MikeFoden** [ardura/Scrollscope#26]
<img width="260" alt="Screenshot 2024-05-09 at 11 08 01 AM" src="https://github.com/ardura/Scrollscope/assets/177184/2eb0b032-7335-4215-9398-7925214a6ecd">

Unfortunately the automated releases will not be able to be opened by Apple.

**Comment by ardura** [comment]
Did you ever figure this one out?

**Comment by AndiLavera** [comment]
This worked for me just now on a M1 Pro with Sonoma 14.5 😄 

Ableton's plugin scanner wouldn't detect the VST and `scrollscope` wasn't searchable until running the following commands.

**Comment by ardura** [comment]
Thanks for the confirmation @AndiLavera I'm glad it's working!
