### ISSUE TITLE
Ardour detailed instructions

### ISSUE THREAD

**Issue by muzzol** [ardura/Scrollscope#27]
this is a feature request for more documentation as I'm not getting any signal processed by the plugin on Ardour.

I can add the plugin to a channel/bus but I don't get anything inside the plugin window.

thanks for your time.

![ardour_scroll](https://github.com/ardura/Scrollscope/assets/6727358/f127a41e-49be-47c3-942b-d85e1f06b9f8)

**Comment by ardura** [comment]
Hey muzzol! I'll have to check my test session for Ardour and see how I set it up. I'm on vacation right now but will get back to you on Wednesday at latest. Thanks!

**Comment by ardura** [comment]
Hey @muzzol here's how I did it. (I'll add this to the main Readme after I post this)

1. Add scrollscope to a mixer track in Ardour

![image](https://github.com/ardura/Scrollscope/assets/31751444/b5c67d0a-ff09-4b13-906b-23b511eebe5d)

2. Select the input routing, then the enable sidechains to Scrollscope

![image](https://github.com/ardura/Scrollscope/assets/31751444/5a966ab8-56fb-41f4-868d-8156f8a64624)

3. Click on the "-" and route another mixer channel as the sidechain

![image](https://github.com/ardura/Scrollscope/assets/31751444/6e978526-f12b-4daa-9420-2564646f5bf0)
![image](https://github.com/ardura/Scrollscope/assets/31751444/e3d23570-5b0a-4888-985f-637b489fc741)

4. Repeat for other inputs but it should work at that point

![image](https://github.com/ardura/Scrollscope/assets/31751444/21ab72a2-c9cd-40fe-a43a-60479dbf9852)

**Comment by muzzol** [comment]
thanks a lot for your time, it works great
