### ISSUE TITLE
Clap Crashing on Bitwig Linux

### ISSUE THREAD

**Issue by acook** [ardura/Scrollscope#28]
The standalone and VST3 versions work fine, but when I add the clap version of Scrollscope to Bitwig the plugin falls over whenever I try to display the window.

- Bitwig 5.2b10
- Solus Linux (Budgie, X11, PipeWire)

**Comment by ardura** [comment]
Hey @acook, thanks for trying out Scrollscope. I'm not too sure where to investigate this since nih_plug(the underlying framework) does the CLAP version export with a single line of code...but I'll see if I can find out more.

**Comment by acook** [comment]
Luckily I had the last stable version of Bitwig available as well and indeed it does work there, so something must have changed in the beta. Very odd! Probably wait until the next stable to see if the issue persists then?

**Comment by acook** [comment]
I just noticed the 5.2 stable came out today - and good news, the issue was fixed by Bitwig!

Thanks for your time and attention!
