### ISSUE TITLE
Add Stereo View

### ISSUE THREAD

**Issue by muzzol** [ardura/Scrollscope#29]
This is a feature request for Stereo View

I'm using scrollscope to visualize my output (no to sync beats) and It would be great to have a stereo view (L/R).

thanks a lot for your time.

**Comment by ardura** [comment]
Hi @muzzol ! Do you mean something like the views stacked with one being L and one being R?
![image](https://github.com/user-attachments/assets/271daf26-af7d-493b-80c0-4cd1c6804c9e)
![image](https://github.com/user-attachments/assets/c05d81e6-c7f5-4621-ad90-d5f6c4fa6e59)

**Comment by muzzol** [comment]
yes, exactly that.

TBH I'm using Simple Scope right now: https://github.com/x42/sisco.lv2

but the owner don't have any plans to add new features, so I'm evaluating alternatives.

my use case is related to analyzing, not beat sync. I'm not sure if you have time to improve that part of the plugin.

**Comment by ardura** [comment]
Yeah that's probably something I can add, are you looking for certain metrics or info as well on the display for your analysis purposes? No promises but I can likely add some if I know what to research heh

**Comment by muzzol** [comment]
> are you looking for certain metrics or info as well on the display for your analysis purposes? 

well, I'm using it mainly for loudness comparison, so it would be nice to have peaks/transients that pass certain treshold in another colour, like a lot of waveform plugins do.

something like this: https://www.audiopluginsforfree.com/wp-content/uploads/2024/01/peakeater-1024x639.jpg

thanks a lot for your time!

**Comment by ardura** [comment]
I was able to do the stereo view, but the only other metrics it has right now is making red lines when the signal starts to clip. Hopefully that is at least somewhat useful for you!

https://github.com/ardura/Scrollscope/releases/tag/v1.4.1
